# Generated by Django 5.2.7 on 2026-03-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_app', '0002_alter_customuser_id_alter_evaluation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('approved', 'approved'), ('reviewed', 'reviewed')], default='draft', max_length=20),
        ),
    ]
